version: '1'

services:
  postgres:
    image: postgres:17.3
    env_file:
      - .env
    ports:
      - "5432:5432"
    container_name: app_posgres_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hw06-network
    volumes:
      - hw06dbdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    container_name: web_app
    restart: on-failure
    networks:
      - hw06-network
    depends_on:
      postgres:
        condition: service_healthy

networks:
  hw06-network:

volumes:
  hw06dbdata: