"""add_last_name_field_to_students

Revision ID: 9a829eeee761
Revises: 43210d99c912
Create Date: 2025-07-13 00:23:54.911237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a829eeee761'
down_revision: Union[str, Sequence[str], None] = '43210d99c912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('students', sa.Column('last_name', sa.String(length=50), nullable=True))
    
    # Update existing records with generated last names
    from faker import Faker
    fake = Faker()
    
    # Get existing student IDs
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM students WHERE last_name IS NULL"))
    student_ids = [row[0] for row in result]
    
    # Generate last names for existing students
    for student_id in student_ids:
        last_name = fake.last_name()
        connection.execute(
            sa.text("UPDATE students SET last_name = :last_name WHERE id = :id"),
            {"last_name": last_name, "id": student_id}
        )
    
    # Now make last_name NOT NULL
    op.alter_column('students', 'last_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'last_name')
    # ### end Alembic commands ###
